[package]
name = "orchiddb-conformance-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
orchiddb = { path = "../.." }
arrow = "58.2.0"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
datafusion = "53.1.0"
duckdb = { version = "1.10502.0", features = ["bundled", "chrono", "vtab-arrow"] }
