"""Executable feature probes. Expected results are authored independently of engines."""
FIXTURE = [
 "CREATE (:Person {uid:1,name:'Alice',age:30})",
 "CREATE (:Person {uid:2,name:'Bob',age:20})",
 "CREATE (:Person {uid:3,name:'Carol',age:40})",
 "CREATE (:Person {uid:4,name:'Dave'})",
 "MATCH (a:Person {uid:1}),(b:Person {uid:2}) CREATE (a)-[:KNOWS {weight:1}]->(b)",
 "MATCH (a:Person {uid:2}),(b:Person {uid:3}) CREATE (a)-[:KNOWS {weight:2}]->(b)",
 "MATCH (a:Person {uid:1}),(b:Person {uid:3}) CREATE (a)-[:KNOWS {weight:3}]->(b)",
 "MATCH (a:Person {uid:3}),(b:Person {uid:1}) CREATE (a)-[:KNOWS {weight:4}]->(b)",
]
TESTS=[]
def add(language,group,key,title,query,expected,ordered=False,**extra):
 TESTS.append(dict(id=f'{language}.{key}',language=language,category=group,title=title,query=query,expected=expected,ordered=ordered,**extra))
def cy(group,key,title,q,e,**kw): add('cypher',group,key,title,q,e,**kw)
def gr(group,key,title,q,values,**kw): add('gremlin',group,key,title,q,[[v] for v in values],**kw)
def sp(group,key,title,q,e,**kw): add('sparql',group,key,title,q,e,**kw)

# Pattern matching and relational semantics.
for key,title,q,e in [
 ('node_scan','Labelled node scan',"MATCH (p:Person) RETURN p.name",[['Alice'],['Bob'],['Carol'],['Dave']]),
 ('all_nodes','Unlabelled node scan','MATCH (p) RETURN count(p)',[[4]]),
 ('property_pattern','Properties inside node pattern',"MATCH (p:Person {name:'Alice'}) RETURN p.age",[[30]]),
 ('directed','Directed expansion',"MATCH (:Person {name:'Alice'})-[:KNOWS]->(p:Person) RETURN p.name",[['Bob'],['Carol']]),
 ('incoming','Incoming expansion',"MATCH (:Person {name:'Alice'})<-[:KNOWS]-(p:Person) RETURN p.name",[['Carol']]),
 ('undirected','Undirected expansion',"MATCH (:Person {name:'Alice'})-[:KNOWS]-(p:Person) RETURN p.name",[['Bob'],['Carol'],['Carol']]),
 ('edge_property','Relationship property projection','MATCH ()-[r:KNOWS]->() RETURN r.weight',[[1],[2],[3],[4]]),
 ('edge_type','Relationship type function','MATCH ()-[r:KNOWS]->() RETURN DISTINCT type(r)',[['KNOWS']]),
 ('join','Two-hop relationship join',"MATCH (:Person {name:'Alice'})-[:KNOWS]->()-[:KNOWS]->(p) RETURN p.name",[['Carol'],['Alice']]),
 ('cartesian','Cartesian product','MATCH (a:Person),(b:Person) RETURN count(*)',[[16]]),
 ('optional','Optional match preserves unmatched row',"MATCH (p:Person {name:'Dave'}) OPTIONAL MATCH (p)-[:KNOWS]->(q) RETURN p.name,q.name",[['Dave',None]]),
 ('optional_predicate','Optional-match predicate stays optional',"MATCH (p:Person {name:'Alice'}) OPTIONAL MATCH (p)-[:KNOWS]->(q) WHERE q.age > 100 RETURN p.name,q.name",[['Alice',None]]),
 ('distinct','DISTINCT on projected values','MATCH ()-[:KNOWS]->(p) RETURN DISTINCT p.name',[['Alice'],['Bob'],['Carol']]),
 ('union','UNION removes duplicates',"RETURN 'x' AS v UNION RETURN 'x' AS v",[['x']]),
 ('union_all','UNION ALL preserves duplicates',"RETURN 'x' AS v UNION ALL RETURN 'x' AS v",[['x'],['x']]),
 ('with','WITH projection and filter','MATCH (p:Person) WITH p.name AS name,p.age AS age WHERE age>25 RETURN name',[['Alice'],['Carol']]),
 ('unwind','UNWIND preserves duplicates','UNWIND [1,1,2] AS x RETURN x',[[1],[1],[2]]),
 ('empty_unwind','UNWIND empty list produces zero rows','UNWIND [] AS x RETURN x',[]),
 ('null_unwind','UNWIND null produces zero rows','UNWIND null AS x RETURN x',[]),
 ('exists_subquery','Correlated EXISTS subquery','MATCH (p:Person) WHERE EXISTS { MATCH (p)-[:KNOWS]->() } RETURN p.name',[['Alice'],['Bob'],['Carol']]),
 ('count_subquery','Correlated COUNT subquery',"MATCH (p:Person {name:'Alice'}) RETURN COUNT { MATCH (p)-[:KNOWS]->() }",[[2]]),
 ('call_subquery','CALL subquery','CALL { RETURN 7 AS x } RETURN x',[[7]]),
 ('correlated_call','Correlated CALL subquery',"MATCH (p:Person {name:'Alice'}) CALL { WITH p MATCH (p)-[:KNOWS]->(q) RETURN q.name AS name } RETURN name",[['Bob'],['Carol']]),
 ('list_subquery','COLLECT subquery',"RETURN COLLECT { MATCH (p:Person) RETURN p.name ORDER BY p.name }",[[['Alice','Bob','Carol','Dave']]]),
 ('pattern_comprehension','Pattern comprehension',"MATCH (p:Person {name:'Alice'}) RETURN size([(p)-[:KNOWS]->(q) | q.name])",[[2]]),
]:cy('Cypher · patterns and clauses',key,title,q,e)
cy('Cypher · patterns and clauses','order','ORDER BY multiple keys','MATCH (p:Person) RETURN p.name ORDER BY p.age DESC,p.name', [['Dave'],['Carol'],['Alice'],['Bob']],ordered=True)
cy('Cypher · patterns and clauses','pagination','SKIP and LIMIT','MATCH (p:Person) RETURN p.name ORDER BY p.name SKIP 1 LIMIT 2',[['Bob'],['Carol']],ordered=True)
for key,title,q,e in [
 ('bounded_path','Bounded variable-length path',"MATCH (:Person {name:'Alice'})-[:KNOWS*1..2]->(p) RETURN p.name",[['Bob'],['Carol'],['Carol'],['Alice']]),
 ('zero_path','Zero-length path',"MATCH (:Person {name:'Alice'})-[:KNOWS*0..0]->(p) RETURN p.name",[['Alice']]),
 ('path_length','Path length',"MATCH p=(:Person {name:'Alice'})-[:KNOWS]->(:Person {name:'Bob'}) RETURN length(p)",[[1]]),
 ('path_nodes','nodes(path)',"MATCH p=(:Person {name:'Alice'})-[:KNOWS]->(:Person {name:'Bob'}) RETURN [n IN nodes(p) | n.name]",[[['Alice','Bob']]]),
 ('path_relationships','relationships(path)',"MATCH p=(:Person {name:'Alice'})-[:KNOWS]->(:Person {name:'Bob'}) RETURN [r IN relationships(p) | r.weight]",[[[1]]]),
 ('trail','Same-MATCH relationship uniqueness (trail)',"MATCH (a:Person {name:'Alice'})-[r:KNOWS]->(b)<-[s:KNOWS]-(a) RETURN count(*)",[[0]]),
 ('shortest','shortestPath function syntax',"MATCH (a:Person {name:'Alice'}),(b:Person {name:'Carol'}),p=shortestPath((a)-[:KNOWS*1..5]->(b)) RETURN length(p)",[[1]]),
 ('all_shortest','allShortestPaths function syntax',"MATCH (a:Person {name:'Alice'}),(b:Person {name:'Carol'}),p=allShortestPaths((a)-[:KNOWS*1..5]->(b)) RETURN length(p)",[[1]]),
 ('qpp','Quantified path pattern',"MATCH (:Person {name:'Alice'}) ((a)-[:KNOWS]->(b)){1,2} RETURN b[-1].name",[['Bob'],['Carol'],['Carol'],['Alice']]),
]:cy('Cypher · paths',key,title,q,e)
for key,title,q,e in [
 ('count_star','count(*) counts rows','MATCH (p:Person) RETURN count(*)',[[4]]),
 ('count_property','count(property) ignores null','MATCH (p:Person) RETURN count(p.age)',[[3]]),
 ('sum','sum numeric values','MATCH (p:Person) RETURN sum(p.age)',[[90]]),
 ('avg','avg numeric values','MATCH (p:Person) RETURN avg(p.age)',[[30]]),
 ('min_max','min and max','MATCH (p:Person) RETURN min(p.age),max(p.age)',[[20,40]]),
 ('collect','collect ignores null','MATCH (p:Person) WITH p ORDER BY p.age RETURN collect(p.age)',[[[20,30,40]]]),
 ('empty_count','Count over empty input','MATCH (p:Person) WHERE p.age>100 RETURN count(*)',[[0]]),
 ('empty_sum','Sum over empty input','MATCH (p:Person) WHERE p.age>100 RETURN sum(p.age)',[[0]]),
 ('group','Implicit grouping','MATCH (p:Person)-[:KNOWS]->(q) RETURN p.name,count(q)',[['Alice',2],['Bob',1],['Carol',1]]),
 ('post_aggregate_filter','Filter after aggregation','MATCH (p:Person)-[:KNOWS]->(q) WITH p.name AS name,count(q) AS n WHERE n>1 RETURN name',[['Alice']]),
 ('percentile_cont','percentileCont','UNWIND [1,2,3,4] AS x RETURN percentileCont(x,0.5)',[[2.5]]),
 ('percentile_disc','percentileDisc','UNWIND [1,2,3,4] AS x RETURN percentileDisc(x,0.5)',[[2]]),
 ('stdev','stDev sample standard deviation','UNWIND [1,2,3] AS x RETURN stDev(x)',[[1.0]]),
]:cy('Cypher · aggregation',key,title,q,e)
for key,title,q,e in [
 ('null_equal','Null equality propagates null','RETURN null = null',[[None]]),
 ('null_logic','Three-valued boolean logic','RETURN null AND false,null OR true,NOT null',[[False,True,None]]),
 ('null_in','Membership with null','RETURN 1 IN [2,null],1 IN [1,null]',[[None,True]]),
 ('coalesce','coalesce','RETURN coalesce(null,3)',[[3]]),
 ('case','Searched CASE','RETURN CASE WHEN 2>1 THEN 7 ELSE 0 END',[[7]]),
 ('simple_case','Simple CASE',"RETURN CASE 2 WHEN 2 THEN 'yes' ELSE 'no' END",[['yes']]),
 ('is_null','IS NULL predicate','MATCH (p:Person) WHERE p.age IS NULL RETURN p.name',[['Dave']]),
 ('list_index','List index and negative index','RETURN [1,2,3][0],[1,2,3][-1]',[[1,3]]),
 ('list_slice','List slicing','RETURN [1,2,3,4][1..3]',[[[2,3]]]),
 ('list_oob','Out-of-range list indexing returns null','RETURN [1][9]',[[None]]),
 ('list_comprehension','List comprehension','RETURN [x IN [1,2,3] WHERE x>1 | x*2]',[[[4,6]]]),
 ('reduce','reduce list fold','RETURN reduce(s=0,x IN [1,2,3] | s+x)',[[6]]),
 ('all','all predicate','RETURN all(x IN [1,2,3] WHERE x>0)',[[True]]),
 ('any','any predicate','RETURN any(x IN [1,2,3] WHERE x>2)',[[True]]),
 ('none','none predicate','RETURN none(x IN [1,2,3] WHERE x>3)',[[True]]),
 ('single','single predicate','RETURN single(x IN [1,2,3] WHERE x=2)',[[True]]),
 ('empty_all','all over empty list','RETURN all(x IN [] WHERE x>0)',[[True]]),
 ('range','range inclusive endpoint','RETURN range(1,3)',[[[1,2,3]]]),
 ('head_last','head and last','RETURN head([1,2]),last([1,2])',[[1,2]]),
 ('tail','tail','RETURN tail([1,2,3])',[[[2,3]]]),
 ('reverse','reverse list','RETURN reverse([1,2,3])',[[[3,2,1]]]),
 ('map_access','Map literal and property access','RETURN {x:7}.x',[[7]]),
 ('mixed_list','Heterogeneous list values',"RETURN [1,'x',true]",[[[1,'x',True]]]),
 ('map_projection','Map projection',"MATCH (p:Person {name:'Alice'}) WITH p{.name,.age} AS m RETURN m.name,m.age",[['Alice',30]]),
 ('keys','keys(map)','RETURN size(keys({x:1,y:2}))',[[2]]),
 ('arithmetic','Arithmetic precedence','RETURN 1+2*3,7%3',[[7,1]]),
 ('integer_division','Integer division','RETURN 5/2',[[2]]),
 ('float_division','Floating-point division','RETURN 5.0/2',[[2.5]]),
 ('cast_integer','toInteger','RETURN toInteger(3.9)',[[3]]),
 ('cast_float','toFloat',"RETURN toFloat('2.5')",[[2.5]]),
 ('cast_boolean','toBoolean',"RETURN toBoolean('true')",[[True]]),
 ('cast_string','toString','RETURN toString(42)',[['42']]),
 ('labels','labels(node)',"MATCH (p:Person {name:'Alice'}) RETURN labels(p)",[[['Person']]]),
]:cy('Cypher · values and expressions',key,title,q,e)
for key,title,q,e in [
 ('string_case','toUpper and toLower',"RETURN toUpper('ab'),toLower('AB')",[['AB','ab']]),
 ('string_trim','trim',"RETURN trim(' ab ')",[['ab']]),
 ('string_replace','replace',"RETURN replace('abc','b','X')",[['aXc']]),
 ('string_split','split',"RETURN split('a,b',',')",[[['a','b']]]),
 ('substring','substring',"RETURN substring('abcd',1,2)",[['bc']]),
 ('starts_ends','STARTS WITH and ENDS WITH',"RETURN 'abcd' STARTS WITH 'ab','abcd' ENDS WITH 'cd'",[[True,True]]),
 ('contains','CONTAINS',"RETURN 'abcd' CONTAINS 'bc'",[[True]]),
 ('regex','Regular expression predicate',"RETURN 'alice' =~ 'a.*'",[[True]]),
 ('unicode_size','Unicode string size',"RETURN size('a😀b')",[[3]]),
 ('math','abs, ceil, floor, sqrt','RETURN abs(-3),ceil(1.2),floor(1.8),sqrt(9)',[[3,2,1,3]]),
 ('pi','pi constant','RETURN round(pi()*1000)',[[3142]]),
 ('date','Date construction and year',"RETURN date('2024-02-29').year",[[2024]]),
 ('duration','Duration construction',"RETURN duration('P2D').days",[[2]]),
 ('datetime','Zoned datetime construction',"RETURN datetime('2024-01-02T03:04:05Z').year",[[2024]]),
 ('point','Spatial point','RETURN point({x:1.0,y:2.0}).x',[[1]]),
]:cy('Cypher · functions',key,title,q,e)
for key,title,q,e in [
 ('create','CREATE node and return property',"CREATE (p:Probe {name:'new'}) RETURN p.name",[['new']]),
 ('merge','MERGE existing node',"MERGE (p:Person {uid:1}) RETURN p.name",[['Alice']]),
 ('set','SET property',"MATCH (p:Person {uid:1}) SET p.score=7 RETURN p.score",[[7]]),
 ('set_map','SET += map',"MATCH (p:Person {uid:1}) SET p += {score:7} RETURN p.score",[[7]]),
 ('remove','REMOVE property',"MATCH (p:Person {uid:1}) SET p.score=7 REMOVE p.score RETURN p.score",[[None]]),
 ('foreach','FOREACH mutation',"MATCH (p:Person {uid:1}) FOREACH (x IN [1,2] | SET p.score=x) RETURN p.score",[[2]]),
 ('delete','DELETE isolated node',"CREATE (p:Probe {name:'gone'}) WITH p DELETE p RETURN 1",[[1]]),
]:cy('Cypher · writes',key,title,q,e,mutates=True)

# Gremlin probes use the same labelled property graph and explicit projected values.
for key,title,q,e in [
 ('v','V node source',"g.V().hasLabel('Person').count()",[4]),
 ('e','E edge source','g.E().count()',[4]),
 ('has','has property equality',"g.V().has('name','Alice').values('age')",[30]),
 ('has_label','hasLabel',"g.V().hasLabel('Person').values('name')",['Alice','Bob','Carol','Dave']),
 ('has_not','hasNot missing property',"g.V().hasNot('age').values('name')",['Dave']),
 ('out','out traversal',"g.V().has('name','Alice').out('KNOWS').values('name')",['Bob','Carol']),
 ('in','in traversal',"g.V().has('name','Alice').in('KNOWS').values('name')",['Carol']),
 ('both','both traversal multiplicity',"g.V().has('name','Alice').both('KNOWS').values('name')",['Bob','Carol','Carol']),
 ('out_e','outE relationship properties',"g.V().has('name','Alice').outE('KNOWS').values('weight')",[1,3]),
 ('in_v','inV endpoint',"g.V().has('name','Alice').outE().inV().values('name')",['Bob','Carol']),
 ('other_v','otherV endpoint',"g.V().has('name','Alice').outE().otherV().values('name')",['Bob','Carol']),
 ('both_v','bothV endpoints',"g.E().has('weight',1).bothV().values('name')",['Alice','Bob']),
 ('label','label projection',"g.V().label().dedup()",['Person']),
 ('identity','identity preserves traversers','g.inject(1,2).identity()',[1,2]),
 ('constant','constant replaces values','g.inject(1,2).constant(7)',[7,7]),
 ('inject','inject source','g.inject(1,2,2)',[1,2,2]),
 ('values','values skips missing properties',"g.V().values('age')",[20,30,40]),
 ('count','count empty input',"g.V().has('name','missing').count()",[0]),
 ('dedup','dedup removes duplicates','g.inject(1,1,2).dedup()',[1,2]),
 ('limit','limit after order','g.inject(3,1,2).order().limit(2)',[1,2]),
 ('range','range after order','g.inject(3,1,2).order().range(1,3)',[2,3]),
 ('tail','tail after order','g.inject(3,1,2).order().tail(2)',[2,3]),
 ('skip','skip after order','g.inject(3,1,2).order().skip(1)',[2,3]),
 ('fold','fold ordered sequence','g.inject(1,2,3).fold()',[[1,2,3]]),
 ('unfold','unfold list','g.inject([1,2,3]).unfold()',[1,2,3]),
 ('sum','sum values','g.inject(1,2,3).sum()',[6]),
 ('mean','mean values','g.inject(1,2,3).mean()',[2]),
 ('min','min values','g.inject(1,2,3).min()',[1]),
 ('max','max values','g.inject(1,2,3).max()',[3]),
 ('group_count','groupCount projected key',"g.inject('a','a','b').groupCount().select('a')",[2]),
 ('group','group by property',"g.V().group().by('name').by(count()).select('Alice')",[1]),
 ('is','is predicate','g.inject(1,2,3).is(gt(1))',[2,3]),
 ('within','within predicate','g.inject(1,2,3).is(within(1,3))',[1,3]),
 ('without','without predicate','g.inject(1,2,3).is(without(1,3))',[2]),
 ('between','between lower inclusive upper exclusive','g.inject(1,2,3).is(between(1,3))',[1,2]),
 ('inside','inside exclusive bounds','g.inject(1,2,3).is(inside(1,3))',[2]),
 ('and','and traversal filter',"g.V().and(has('age',gt(20)),has('age',lt(40))).values('name')",['Alice']),
 ('or','or traversal filter',"g.V().or(has('name','Alice'),has('name','Dave')).values('name')",['Alice','Dave']),
 ('not','not traversal filter',"g.V().not(out('KNOWS')).values('name')",['Dave']),
 ('where','where nested traversal',"g.V().where(out('KNOWS').has('name','Bob')).values('name')",['Alice']),
 ('select','as and select bindings',"g.V().has('name','Alice').as('a').out().select('a').values('name')",['Alice','Alice']),
 ('project','project and by',"g.V().has('name','Alice').project('n').by('name').select('n')",['Alice']),
 ('value_map','valueMap property shape',"g.V().has('name','Alice').valueMap('name').select('name')",[['Alice']]),
 ('element_map','elementMap property shape',"g.V().has('name','Alice').elementMap('name').select('name')",['Alice']),
 ('union','union preserves duplicate traversers','g.inject(1).union(identity(),identity())',[1,1]),
 ('coalesce','coalesce selects first productive branch','g.inject(1).coalesce(filter(is(2)),constant(7))',[7]),
 ('choose','choose branches','g.inject(1,2).choose(is(1),constant(7),constant(8))',[7,8]),
 ('optional','optional retains unmatched input',"g.V().has('name','Dave').optional(out()).values('name')",['Dave']),
 ('local','local scopes reduction','g.inject([1,2],[3]).local(unfold().sum())',[3,3]),
 ('repeat','repeat times exact hops',"g.V().has('name','Alice').repeat(out('KNOWS')).times(2).values('name')",['Carol','Alice']),
 ('emit','repeat emit intermediate traversers',"g.V().has('name','Alice').repeat(out('KNOWS')).emit().times(2).values('name')",['Bob','Carol','Carol','Alice']),
 ('until','repeat until predicate',"g.V().has('name','Bob').repeat(out('KNOWS')).until(has('name','Alice')).values('name')",['Alice']),
 ('loops','repeat loop counter',"g.V().has('name','Bob').repeat(out('KNOWS')).until(loops().is(2)).values('name')",['Alice']),
 ('simple_path','simplePath rejects repeated vertices',"g.V().has('name','Alice').repeat(out('KNOWS')).times(2).simplePath().values('name')",['Carol']),
 ('cyclic_path','cyclicPath selects repeated vertices',"g.V().has('name','Alice').repeat(out('KNOWS')).times(2).cyclicPath().values('name')",['Alice']),
 ('path','path with by projection',"g.V().has('name','Alice').out().has('name','Bob').path().by('name').unfold()",['Alice','Bob']),
 ('aggregate','aggregate and cap side effect',"g.inject(1,2).aggregate('x').cap('x').unfold()",[1,2]),
 ('store','store and cap side effect',"g.inject(1,2).store('x').cap('x').unfold()",[1,2]),
 ('sack','withSack and sack addition','g.withSack(1).inject(2).sack(sum).by(constant(3)).sack()',[4]),
 ('barrier','barrier preserves multiplicity','g.inject(1,1,2).barrier().count()',[3]),
 ('empty_fold','fold over empty traversal',"g.V().has('name','missing').fold()",[[]]),
 ('empty_sum','sum over empty traversal',"g.V().has('name','missing').values('age').sum()",[]),
 ('null','Unfolded null is productive','g.inject([null]).unfold().count()',[1]),
 ('missing_order','Order by nonexistent property',"g.V().order().by('nonexistent').count()",[0]),
 ('text_predicate','TextP startingWith',"g.V().has('name',startingWith('Al')).values('name')",['Alice']),
 ('math','math expression','g.inject(3).math("_ * 2")',[6]),
 ('match','match traversal binding',"g.V().has('name','Alice').match(__.as('a').out('KNOWS').as('b')).select('b').values('name')",['Bob','Carol']),
]:gr('Gremlin · traversal and semantics',key,title,q,e)
gr('Gremlin · traversal and semantics','order','order ascending','g.inject(3,1,2).order()',[1,2,3],ordered=True)
gr('Gremlin · traversal and semantics','order_desc','order descending','g.inject(3,1,2).order().by(desc)',[3,2,1],ordered=True)
for key,title,q,e in [
 ('add_v','addV creates vertex',"g.addV('Probe').property('name','new').values('name')",['new']),
 ('property','property assignment',"g.V().has('name','Alice').property('score',7).values('score')",[7]),
 ('multi_property','Vertex list cardinality',"g.addV('Probe').property(list,'tag','a').property(list,'tag','b').values('tag')",['a','b']),
 ('meta_property','Vertex meta-property',"g.addV('Probe').property('tag','a','since',2020).properties('tag').values('since')",[2020]),
]:gr('Gremlin · writes and property model',key,title,q,e,mutates=True)

PREFIX='PREFIX ex: <https://example.com/> '
for key,title,q,e in [
 ('select','SELECT mapped property','SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name . }',[['Alice'],['Bob'],['Carol'],['Dave']]),
 ('filter','FILTER numeric comparison','SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name ; ex:age ?age . FILTER(?age>25) }',[['Alice'],['Carol']]),
 ('join','Join triple patterns','SELECT ?name WHERE { ?p a ex:Person ; ex:name "Alice" ; ex:knows ?q . ?q ex:name ?name . }',[['Bob'],['Carol']]),
 ('optional','OPTIONAL unbound value','SELECT ?name ?age WHERE { ?p a ex:Person ; ex:name ?name . OPTIONAL { ?p ex:age ?age . } FILTER(?name="Dave") }',[['Dave',None]]),
 ('distinct','DISTINCT projection','SELECT DISTINCT ?name WHERE { ?p ex:knows ?q . ?q ex:name ?name . }',[['Alice'],['Bob'],['Carol']]),
 ('union','UNION solution multiplicity','SELECT ?x WHERE { { BIND(1 AS ?x) } UNION { BIND(1 AS ?x) } }',[[1],[1]]),
 ('values','VALUES inline table','SELECT ?x WHERE { VALUES ?x { 1 2 3 } }',[[1],[2],[3]]),
 ('bind','BIND expression','SELECT ?x WHERE { BIND(1+2 AS ?x) }',[[3]]),
 ('count','COUNT aggregate','SELECT (COUNT(?p) AS ?n) WHERE { ?p a ex:Person . }',[[4]]),
 ('sum','SUM aggregate','SELECT (SUM(?age) AS ?n) WHERE { ?p a ex:Person ; ex:age ?age . }',[[90]]),
 ('ask','ASK boolean','ASK WHERE { ?p a ex:Person ; ex:name "Alice" . }',[[True]]),
 ('not_exists','FILTER NOT EXISTS','SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name . FILTER NOT EXISTS { ?p ex:knows ?q . } }',[['Dave']]),
 ('bound','BOUND on optional variable','SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name . OPTIONAL { ?p ex:age ?age . } FILTER(!BOUND(?age)) }',[['Dave']]),
 ('minus','MINUS with shared binding','SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name . MINUS { ?p ex:age 30 . } }',[['Bob'],['Carol'],['Dave']]),
 ('str','STR lexical form','SELECT ?s WHERE { BIND(STR(ex:Alice) AS ?s) }',[['https://example.com/Alice']]),
 ('regex','REGEX string filter','SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name . FILTER(REGEX(?name,"^A")) }',[['Alice']]),
]:sp('SPARQL · query algebra',key,title,PREFIX+q,e)
sp('SPARQL · query algebra','order','ORDER BY and LIMIT',PREFIX+'SELECT ?name WHERE { ?p a ex:Person ; ex:name ?name . } ORDER BY ?name LIMIT 2',[['Alice'],['Bob']],ordered=True)

if __name__=='__main__':
 import json
 from pathlib import Path
 Path(__file__).with_name('probes.json').write_text(json.dumps({'fixture':FIXTURE,'tests':TESTS},indent=2)+'\n')
 print(f'{len(TESTS)} executable feature probes')
