//! Capture plans from executed queries: cargo run --features duckdb --example mapped_execution_plans
#[cfg(feature = "duckdb")]
#[tokio::main]
async fn main() -> Result<(), String> {
    use orchiddb::{
        engine::GraphEngine,
        ir::rel::mapping::{EdgeMapping, GraphMapping, NodeMapping},
    };
    use std::sync::Arc;
    let ddl = "CREATE TABLE people(id VARCHAR PRIMARY KEY, name VARCHAR, unused VARCHAR);\nINSERT INTO people SELECT 'p'||i, 'name'||i, repeat('x',100) FROM range(10000) t(i);\nCREATE TABLE links(id VARCHAR PRIMARY KEY, src VARCHAR, dst VARCHAR);\nINSERT INTO links SELECT 'e'||i, 'p'||i, 'p'||(i+1) FROM range(9999) t(i);\nCREATE VIEW unrelated AS SELECT error('unrelated mapping was scanned')::VARCHAR AS id FROM range(1);";
    let db = duckdb::Connection::open_in_memory().map_err(|e| e.to_string())?;
    db.execute_batch(ddl).map_err(|e| e.to_string())?;
    let verify = db.try_clone().map_err(|e| e.to_string())?;
    let mut mapping = GraphMapping::new();
    mapping.map_node(
        NodeMapping::table("Person", "people", "id")
            .property("id", "id")
            .property("name", "name"),
    );
    mapping.map_node(NodeMapping::table("Unrelated", "unrelated", "id"));
    mapping.map_edge(
        EdgeMapping::table("LINK", "links", "src", "dst", "Person", "Person").with_id("id"),
    );
    let mut engine = GraphEngine::mapped(db, Arc::new(mapping))?;
    println!(
        "# Executed mapped query plans\n\nGenerated by `RUST_MIN_STACK=16777216 cargo run --features duckdb --example mapped_execution_plans`.\n\nThese are runtime physical DAGs and SQL recorded by actual `GraphEngine::mapped` executions, before DuckDB internal optimization. Native source row counts exclude SQL island output. SQL listings do not include transaction control, schema discovery, or persistence DML.\n\n## Fixture\n\n```sql\n{ddl}\n```\n\nMapping: `Person` → `people`, primary key `id`, properties `id` and `name`; `LINK` → `links`, primary key `id`, source `src`, destination `dst`, both endpoints `Person`; `Unrelated` → `unrelated`, primary key `id`. The `unused` column is deliberately unmapped. The unrelated view throws if its rows are scanned.\n"
    );
    let queries = [
        (
            "Selective lookup",
            "MATCH (p:Person {id:'p42'}) RETURN p.name",
            vec![vec!["name42"]],
        ),
        (
            "One-hop join",
            "MATCH (a:Person {id:'p42'})-[:LINK]->(b:Person) RETURN a.name,b.name",
            vec![vec!["name42", "name43"]],
        ),
        (
            "Aggregate",
            "MATCH (p:Person) WHERE p.id IN ['p42','p43','p44'] RETURN count(p) AS n",
            vec![vec!["3"]],
        ),
        (
            "Bounded variable-length traversal",
            "MATCH (a:Person {id:'p42'})-[:LINK*1..3]->(b:Person) RETURN b.name ORDER BY b.name",
            vec![vec!["name43"], vec!["name44"], vec!["name45"]],
        ),
        (
            "Path-value native boundary",
            "MATCH p=(a:Person {id:'p42'})-[:LINK*1..3]->(b:Person) RETURN length(p) AS hops,b.name ORDER BY hops",
            vec![
                vec!["1", "name43"],
                vec!["2", "name44"],
                vec!["3", "name45"],
            ],
        ),
        (
            "List comprehension after joined aggregation",
            "MATCH (a:Person {id:'p42'})-[:LINK*1..3]->(b:Person) WITH a.name AS origin, collect(b.name) AS names RETURN origin, [n IN names WHERE size(n)>0 | toUpper(n)] AS names",
            vec![vec!["name42", "[NAME43,NAME44,NAME45]"]],
        ),
        (
            "Correlated optional match and list comprehension",
            "MATCH (a:Person) WHERE a.id IN ['p42','p9999'] OPTIONAL MATCH (a)-[:LINK]->(b:Person) WITH a.id AS person,collect(b.name) AS names RETURN person,[name IN names WHERE size(name)>0 | toUpper(name)] AS neighbors ORDER BY person",
            vec![vec!["p42", "[NAME43]"], vec!["p9999", "[]"]],
        ),
        (
            "SQL inside a lateral path subplan",
            "UNWIND [1,2] AS x MATCH p=(a:Person {id:'p42'})-[:LINK*1..2]->(b:Person) RETURN x,length(p) AS hops,b.name ORDER BY x,hops",
            vec![
                vec!["1", "1", "name43"],
                vec!["1", "2", "name44"],
                vec!["2", "1", "name43"],
                vec!["2", "2", "name44"],
            ],
        ),
        (
            "Mapped update",
            "MATCH (p:Person {id:'p42'}) SET p.name='changed' RETURN p.name",
            vec![vec!["changed"]],
        ),
    ];
    let mut failures = Vec::new();
    for (title, query, expected) in queries {
        println!("## {title}\n\n```cypher\n{query}\n```\n");
        let result = match engine.cypher(query).await {
            Ok(r) => r,
            Err(e) => {
                println!("Execution failed: `{e}`\n");
                failures.push(format!("{title}: {e}"));
                continue;
            }
        };
        let rows = (0..result.returned.batch.num_rows())
            .map(|row| {
                result
                    .returned
                    .batch
                    .columns()
                    .iter()
                    .map(|c| {
                        arrow::util::display::array_value_to_string(c, row)
                            .map_err(|e| e.to_string())
                    })
                    .collect::<Result<Vec<_>, _>>()
            })
            .collect::<Result<Vec<_>, _>>()?;
        assert_eq!(rows, expected, "{title}");
        let stats = result.stats;
        assert!(stats.islands > 0, "{title}: no SQL island");
        assert!(
            stats.native_source_rows < 20,
            "{title}: excessive native source rows: {}",
            stats.native_source_rows
        );
        assert!(
            stats.native_source_queries.len() < 20,
            "{title}: excessive source requests"
        );
        assert!(
            stats
                .sql_queries
                .iter()
                .chain(&stats.native_source_queries)
                .all(|s| !s.contains("unrelated") && !s.contains("unused")),
            "{title}"
        );
        println!(
            "Result: `{rows:?}`. SQL islands: {}; residual logical operators: {}; native source fetches: {}; native source rows: {}.\n\n```text\n{}```\n",
            stats.islands,
            stats.datafusion_ops,
            stats.native_source_queries.len(),
            stats.native_source_rows,
            stats.physical_plan
        );
        for (i, sql) in stats.sql_queries.iter().enumerate() {
            println!("Island {}:\n\n```sql\n{sql}\n```\n", i + 1);
        }
        for (i, sql) in stats.native_source_queries.iter().enumerate() {
            println!("Native source fetch {}:\n\n```sql\n{sql}\n```\n", i + 1);
        }
    }
    let persisted: String = verify
        .query_row("SELECT name FROM people WHERE id='p42'", [], |r| r.get(0))
        .map_err(|e| e.to_string())?;
    assert_eq!(persisted, "changed");
    println!(
        "Direct DuckDB verification after update: `SELECT name FROM people WHERE id='p42'` returned `{persisted}`. All result assertions passed.\n"
    );
    if !failures.is_empty() {
        return Err(failures.join("; "));
    }
    Ok(())
}
#[cfg(not(feature = "duckdb"))]
fn main() {
    eprintln!("This example requires --features duckdb");
}
